freebsd_instance:
  image_family: freebsd-13-0

task:
  install_script: pkg install -y ghc hs-cabal-install
  script:
    - export LC_ALL=C.UTF-8
    - uname -a # check platform
    - getconf LONG_BIT # check bitness
    - cabal --version
    - cabal update
    - cabal build
